import type { LevelConfig } from "./types";

export const LEVEL_CONFIGS: Record<number, LevelConfig> = {
  1: {
    id: 1,
    name: "Ada / Islak Kıyı",
    locationLabel: "BÖLGE: SAHIL",
    theme: "beach",
    colors: {
      skyTop: "#0a1520",
      skyBottom: "#1a2a3a",
      floorTone: "#1a1e2a",
      wallTone: "#141a24",
      lightAccent: "rgba(255,60,60,0.15)",
      fogColor: "rgba(100,140,160,0.28)",
    },
    effects: {
      fogDensity: "light",
      glitchAmount: "none",
      vignetteColor: "rgba(10,20,30,0.7)",
      particles: "mist",
      shakeMultiplier: 1.0,
      scanlines: false,
      redLightIntensity: "faint",
    },
    ambience: {
      type: "waves",
      droneFreq: 56,
      tempo: "slow",
    },
    systemMessage: "VERİ YÜKLENDİ",
    hint: "Sisli kıyıda yabancı bir ses. Kapılardan biri seni geçirecek.",
    doorVariation: "normal",
  },
  2: {
    id: 2,
    name: "Patika / Çalılık Hat",
    locationLabel: "BÖLGE: PATIKA",
    theme: "path",
    colors: {
      skyTop: "#080f18",
      skyBottom: "#131c28",
      floorTone: "#111620",
      wallTone: "#0e1419",
      lightAccent: "rgba(180,120,60,0.12)",
      fogColor: "rgba(60,80,60,0.32)",
    },
    effects: {
      fogDensity: "medium",
      glitchAmount: "none",
      vignetteColor: "rgba(5,10,5,0.75)",
      particles: "dust",
      shakeMultiplier: 1.0,
      scanlines: false,
      redLightIntensity: "faint",
    },
    ambience: {
      type: "wind",
      droneFreq: 62,
      tempo: "slow",
    },
    systemMessage: "ACCESS DENIED",
    hint: "Patika daraldı. Birinin yürüdüğünü hissediyorsun ama kimseyi göremiyorsun.",
    doorVariation: "worn",
  },
  3: {
    id: 3,
    name: "Orman Girişi",
    locationLabel: "BÖLGE: ORMAN",
    theme: "forest",
    colors: {
      skyTop: "#050c10",
      skyBottom: "#0d1820",
      floorTone: "#0a1018",
      wallTone: "#080d14",
      lightAccent: "rgba(60,120,80,0.10)",
      fogColor: "rgba(40,70,50,0.45)",
    },
    effects: {
      fogDensity: "heavy",
      glitchAmount: "subtle",
      vignetteColor: "rgba(5,8,5,0.82)",
      particles: "mist",
      shakeMultiplier: 1.1,
      scanlines: false,
      redLightIntensity: "faint",
    },
    ambience: {
      type: "forest",
      droneFreq: 68,
      tempo: "slow",
    },
    systemMessage: "HATA: ???",
    hint: "Ağaçlar, sis. Kapılar birbirine benziyor. Yön hissin kayboldu.",
    doorVariation: "worn",
  },
  4: {
    id: 4,
    name: "Gökdelen Dışı / Giriş",
    locationLabel: "BÖLGE: DIŞ CEPHE",
    theme: "exterior",
    colors: {
      skyTop: "#050a14",
      skyBottom: "#0c1520",
      floorTone: "#131822",
      wallTone: "#0f141e",
      lightAccent: "rgba(255,30,30,0.20)",
      fogColor: "rgba(80,80,100,0.35)",
    },
    effects: {
      fogDensity: "medium",
      glitchAmount: "subtle",
      vignetteColor: "rgba(8,5,8,0.78)",
      particles: "dust",
      shakeMultiplier: 1.2,
      scanlines: false,
      redLightIntensity: "pulse",
    },
    ambience: {
      type: "city",
      droneFreq: 72,
      tempo: "medium",
    },
    hint: "Gökdelen netleşiyor. Kapı sesleri fazla yakın geliyor.",
    doorVariation: "worn",
  },
  5: {
    id: 5,
    name: "Checkpoint Katı",
    locationLabel: "KAT: 5 — KONTROL NOKTASI",
    theme: "checkpoint",
    colors: {
      skyTop: "#040810",
      skyBottom: "#0a1018",
      floorTone: "#0f1420",
      wallTone: "#0c1118",
      lightAccent: "rgba(255,180,0,0.12)",
      fogColor: "rgba(100,100,120,0.30)",
    },
    effects: {
      fogDensity: "medium",
      glitchAmount: "moderate",
      vignetteColor: "rgba(8,8,12,0.80)",
      particles: "static",
      shakeMultiplier: 1.3,
      scanlines: true,
      redLightIntensity: "pulse",
    },
    ambience: {
      type: "hum",
      droneFreq: 78,
      tempo: "medium",
    },
    systemMessage: "ANOMALİ ALGILANDI",
    hint: "İlk ağır lanet riski. Burası bir kayıt noktası — geçersen geri dönüş aynı olmaz.",
    doorVariation: "chained",
  },
  6: {
    id: 6,
    name: "Uzun Koridor",
    locationLabel: "KAT: 6 — KORİDOR",
    theme: "corridor",
    colors: {
      skyTop: "#030708",
      skyBottom: "#080d12",
      floorTone: "#0d1118",
      wallTone: "#0a0e15",
      lightAccent: "rgba(200,160,80,0.10)",
      fogColor: "rgba(80,80,80,0.40)",
    },
    effects: {
      fogDensity: "heavy",
      glitchAmount: "moderate",
      vignetteColor: "rgba(6,6,10,0.82)",
      particles: "dust",
      shakeMultiplier: 1.3,
      scanlines: true,
      redLightIntensity: "pulse",
    },
    ambience: {
      type: "echo",
      droneFreq: 82,
      tempo: "medium",
    },
    systemMessage: "SİNYAL KAYBI",
    hint: "Tekrarlayan kapılar. Duvar kağıdı aynı ama lekeler farklı. Kapılar karışıyor.",
    doorVariation: "blank",
  },
  7: {
    id: 7,
    name: "Asansör Önü",
    locationLabel: "KAT: 7 — ASANSÖR",
    theme: "elevator",
    colors: {
      skyTop: "#020508",
      skyBottom: "#060a10",
      floorTone: "#0a0e18",
      wallTone: "#080c14",
      lightAccent: "rgba(255,80,30,0.14)",
      fogColor: "rgba(60,60,80,0.45)",
    },
    effects: {
      fogDensity: "heavy",
      glitchAmount: "heavy",
      vignetteColor: "rgba(5,4,8,0.85)",
      particles: "embers",
      shakeMultiplier: 1.5,
      scanlines: true,
      redLightIntensity: "strong",
    },
    ambience: {
      type: "machine",
      droneFreq: 88,
      tempo: "tense",
    },
    systemMessage: "BELLEK TAŞMASI",
    hint: "Bozuk kat ekranı. Paslı kapı. Bir sonraki seçimde risk artıyor.",
    doorVariation: "chained",
  },
  8: {
    id: 8,
    name: '"Boş Kat"',
    locationLabel: "KAT: 8 — BOŞ ALAN",
    theme: "empty",
    colors: {
      skyTop: "#020406",
      skyBottom: "#050810",
      floorTone: "#080c14",
      wallTone: "#060a10",
      lightAccent: "rgba(180,200,220,0.06)",
      fogColor: "rgba(120,130,150,0.20)",
    },
    effects: {
      fogDensity: "light",
      glitchAmount: "subtle",
      vignetteColor: "rgba(4,5,8,0.88)",
      particles: "none",
      shakeMultiplier: 1.2,
      scanlines: false,
      redLightIntensity: "faint",
    },
    ambience: {
      type: "silence",
      droneFreq: 42,
      tempo: "slow",
    },
    systemMessage: "SYNC OK",
    hint: "Neredeyse boş alan. Yankı var. Sessizlik seni tedirgin ediyor — bu ironik bir rahatlama.",
    doorVariation: "blank",
  },
  9: {
    id: 9,
    name: "İz Katı",
    locationLabel: "KAT: 9 — İZLER",
    theme: "trace",
    colors: {
      skyTop: "#030406",
      skyBottom: "#060810",
      floorTone: "#0a0c14",
      wallTone: "#080a12",
      lightAccent: "rgba(200,100,60,0.16)",
      fogColor: "rgba(80,60,60,0.50)",
    },
    effects: {
      fogDensity: "heavy",
      glitchAmount: "heavy",
      vignetteColor: "rgba(6,4,4,0.88)",
      particles: "ash",
      shakeMultiplier: 1.6,
      scanlines: true,
      redLightIntensity: "strong",
    },
    ambience: {
      type: "static",
      droneFreq: 94,
      tempo: "tense",
    },
    systemMessage: "KAT KAYMASI",
    hint: "Zeminde izler. Kirli duvar. Eski el izleri. Lanet ihtimali yükseliyor.",
    doorVariation: "cursed",
  },
  10: {
    id: 10,
    name: "Çatı Kapısı / Son Seçim",
    locationLabel: "KAT: 10 — ÇATI",
    theme: "roof",
    colors: {
      skyTop: "#020304",
      skyBottom: "#050608",
      floorTone: "#0c0e14",
      wallTone: "#0a0c10",
      lightAccent: "rgba(255,20,20,0.25)",
      fogColor: "rgba(100,80,80,0.55)",
    },
    effects: {
      fogDensity: "extreme",
      glitchAmount: "heavy",
      vignetteColor: "rgba(8,3,3,0.90)",
      particles: "embers",
      shakeMultiplier: 2.0,
      scanlines: true,
      redLightIntensity: "strong",
    },
    ambience: {
      type: "static",
      droneFreq: 100,
      tempo: "tense",
    },
    hint: "Metal kapı. Rüzgâr. Sis. Kırmızı ikaz ışığı. Son seçim sert — yanlış = büyük bedel.",
    doorVariation: "cursed",
  },
};

export function getLevelConfig(level: number): LevelConfig {
  return LEVEL_CONFIGS[Math.max(1, Math.min(10, level))] ?? LEVEL_CONFIGS[1];
}
